FROM node:alpine

WORKDIR /app

ARG MEDUSA_ADMIN_ONBOARDING_TYPE=${MEDUSA_ADMIN_ONBOARDING_TYPE}
ARG STORE_CORS=${STORE_CORS}
ARG ADMIN_CORS=${ADMIN_CORS}
ARG AUTH_CORS=${AUTH_CORS}
ARG REDIS_URL=${REDIS_URL}
ARG JWT_SECRET=${JWT_SECRET}
ARG COOKIE_SECRET=${COOKIE_SECRET}
ARG DATABASE_URL=${DATABASE_URL}
ARG MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY=${MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY}
ARG REDIS_URL=${REDIS_URL}

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

RUN yarn predeploy

CMD ["yarn", "run", "start"]