FROM node:alpine AS build

WORKDIR /app

ARG STORE_CORS=${STORE_CORS} \
    ADMIN_CORS=${ADMIN_CORS} \
    AUTH_CORS=${AUTH_CORS} \
    JWT_SECRET=${JWT_SECRET} \
    COOKIE_SECRET=${COOKIE_SECRET} \
    DATABASE_URL=${DATABASE_URL} \
    REDIS_URL=${REDIS_URL} \
    DISABLE_MEDUSA_ADMIN=true

COPY package.json ./

RUN npm install

COPY . .

RUN npm run build && npm run telemetry && npm run migrate

ENV NODE_ENV=production

EXPOSE 9000

CMD ["npm", "run", "start"]