FROM node:alpine AS build

WORKDIR /app

ARG ADMIN_CORS=${ADMIN_CORS}
ARG MEDUSA_BACKEND_URL=${MEDUSA_BACKEND_URL}
ARG DISABLE_MEDUSA_ADMIN=false

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build --admin-only && npm run telemetry

RUN npm prune --production

FROM node:alpine

COPY --from=build /app/.medusa/server/public/admin ./public

RUN npm install -g serve

EXPOSE 80

CMD ["serve", "-s", "public", "-l", "80"]